baseURL = ""
languageCode = "en-us"
title = "Example YinYong Blog"
theme = "yinyang"
DefaultContentLanguage = "en"
themesDir = "themes"
publishDir = "public"

[author]
name = "Joway Wang"
homepage = "https://joway.io/"

[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1

[languages.cn]
contentDir = "content/cn"
languageName = "Chinese"
weight = 1

[params]
disqus = "joway"
extraHead = ""
mainSections = [ "posts" ]

  [[params.socials]]
  name = "RSS"
  link = "/index.xml"

  [[params.socials]]
  name = "About"
  link = "https://joway.io"
